[package]
name = "diffsplit"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "diffsplit"
path = "src/main.rs"

[dependencies]
eframe = "0.32.3"
egui = "0.32.3"
git2 = "0.18"
diff = "0.1"
similar = "2.6"
anyhow = "1.0"
winit = "0.30.12"
icrate = "0.1"
objc2 = "0.5"
kurbo = "0.9"
imara-diff = "0.2"
